(() => {
  const translations = {
    es: { 'nav.home':'Inicio','nav.categories':'Categorías','nav.cta':'Solicitar un plan','hero.eyebrow':'MUEBLES · ABASTECIMIENTO EN CHINA','hero.title':'Muebles listos para su mercado.','hero.text':'ROYAL UNION coordina el abastecimiento de muebles, desde el brief y la comparación de proveedores hasta las muestras, el control de calidad, la consolidación y la entrega.','hero.primary':'Enviar requisitos','hero.secondary':'Ver categorías','section.eyebrow':'ALCANCE DE CATEGORÍA','section.title':'Empiece por el uso. Después defina la especificación.','section.text':'Los muebles deben coincidir con el espacio, el material, la construcción, el embalaje, las pruebas y el mercado de destino.','cat.1':'Muebles para el hogar','cat.2':'Muebles de oficina','cat.3':'Muebles de exterior','cat.4':'Almacenamiento y estanterías','cat.5':'Muebles comerciales','cat.6':'Muebles para niños','control.title':'Controle los detalles que determinan el costo y la calidad.','process.title':'Una ruta desde el brief hasta la entrega.','faq.title':'Preguntas frecuentes sobre muebles','cta.title':'Envíenos su brief de muebles.','cta.text':'Incluya fotos, dimensiones, material, cantidad, embalaje, destino y plazo.','cta.wa':'WhatsApp','cta.email':'Correo'},
    'pt-BR': { 'nav.home':'Início','nav.categories':'Categorias','nav.cta':'Solicitar um plano','hero.eyebrow':'MÓVEIS · SOURCING NA CHINA','hero.title':'Móveis prontos para o seu mercado.','hero.text':'A ROYAL UNION coordena o sourcing de móveis, do briefing e comparação de fornecedores até amostras, controle de qualidade, consolidação e entrega.','hero.primary':'Enviar requisitos','hero.secondary':'Ver categorias','section.eyebrow':'ESCOPO DA CATEGORIA','section.title':'Comece pelo uso. Depois defina a especificação.','section.text':'Os móveis precisam corresponder ao espaço, material, construção, embalagem, testes e mercado de destino.','cat.1':'Móveis residenciais','cat.2':'Móveis de escritório','cat.3':'Móveis externos','cat.4':'Armazenamento e prateleiras','cat.5':'Móveis comerciais','cat.6':'Móveis infantis','control.title':'Controle os detalhes que determinam custo e qualidade.','process.title':'Uma rota do briefing à entrega.','faq.title':'Perguntas frequentes sobre móveis','cta.title':'Envie seu briefing de móveis.','cta.text':'Inclua fotos, dimensões, material, quantidade, embalagem, destino e prazo.','cta.wa':'WhatsApp','cta.email':'E-mail'},
    ru: { 'nav.home':'Главная','nav.categories':'Категории','nav.cta':'Получить план','hero.eyebrow':'МЕБЕЛЬ · ЗАКУПКИ В КИТАЕ','hero.title':'Мебель, подготовленная для вашего рынка.','hero.text':'ROYAL UNION координирует закупки мебели: от технического задания и сравнения поставщиков до образцов, контроля качества, консолидации и доставки.','hero.primary':'Отправить требования','hero.secondary':'Смотреть категории','section.eyebrow':'КАТЕГОРИИ','section.title':'Начните с применения. Затем определите спецификацию.','section.text':'Мебель должна соответствовать пространству, материалам, конструкции, упаковке, испытаниям и целевому рынку.','cat.1':'Домашняя мебель','cat.2':'Офисная мебель','cat.3':'Уличная мебель','cat.4':'Хранение и стеллажи','cat.5':'Коммерческая мебель','cat.6':'Детская мебель','control.title':'Контролируйте детали, определяющие стоимость и качество.','process.title':'Один путь от задания до доставки.','faq.title':'Вопросы о закупке мебели','cta.title':'Отправьте нам задание на мебель.','cta.text':'Приложите фото, размеры, материал, количество, упаковку, рынок и сроки.','cta.wa':'WhatsApp','cta.email':'Email'},
    'zh-CN': { 'nav.home':'首页','nav.categories':'产品类目','nav.cta':'获取采购方案','hero.eyebrow':'家具 · 中国采购','hero.title':'为您的市场打造合适的家具产品。','hero.text':'ROYAL UNION 从需求梳理、供应商比较，到打样、质量控制、集货和交付，统筹家具采购流程。','hero.primary':'发送采购需求','hero.secondary':'查看分类','section.eyebrow':'品类范围','section.title':'先确认使用场景，再定义产品规格。','section.text':'家具采购需要明确空间、材料、结构、包装、测试和目的市场要求。','cat.1':'家居家具','cat.2':'办公家具','cat.3':'户外家具','cat.4':'收纳与置物架','cat.5':'商业家具','cat.6':'儿童家具','control.title':'控制决定成本与质量的关键细节。','process.title':'从需求到交付的一体化路径。','faq.title':'家具采购常见问题','cta.title':'把家具采购需求发给我们。','cta.text':'请提供图片、尺寸、材料、数量、包装、目的市场和交期。','cta.wa':'WhatsApp 联系','cta.email':'发送邮件'},
    fr: { 'nav.home':'Accueil','nav.categories':'Catégories','nav.cta':'Obtenir un plan','hero.eyebrow':'MOBILIER · SOURCING EN CHINE','hero.title':'Du mobilier adapté à votre marché.','hero.text':'ROYAL UNION coordonne le sourcing de mobilier, du brief et de la comparaison des fournisseurs aux échantillons, au contrôle qualité, à la consolidation et à la livraison.','hero.primary':'Envoyer le brief','hero.secondary':'Voir les catégories','section.eyebrow':'PÉRIMÈTRE DE CATÉGORIE','section.title':'Commencez par l’usage. Définissez ensuite la spécification.','section.text':'Le mobilier doit correspondre à l’espace, aux matériaux, à la construction, à l’emballage, aux essais et au marché de destination.','cat.1':'Mobilier de maison','cat.2':'Mobilier de bureau','cat.3':'Mobilier extérieur','cat.4':'Rangement et étagères','cat.5':'Mobilier commercial','cat.6':'Mobilier enfant','control.title':'Contrôlez les détails qui déterminent coût et qualité.','process.title':'Un parcours du brief à la livraison.','faq.title':'FAQ sourcing mobilier','cta.title':'Envoyez-nous votre brief mobilier.','cta.text':'Ajoutez photos, dimensions, matériau, quantité, emballage, destination et délai.','cta.wa':'WhatsApp','cta.email':'E-mail'}
  };
  const params = new URLSearchParams(location.search);
  const chosen = params.get('lang') || localStorage.getItem('ru-language') || 'en';
  const supported = ['en','es','pt-BR','ru','zh-CN','fr'];
  const locale = supported.includes(chosen) ? chosen : 'en';
  document.documentElement.lang = locale;
  const select = document.querySelector('#language-select');
  if (select) {
    select.value = locale;
    select.addEventListener('change', () => { localStorage.setItem('ru-language', select.value); const next = new URL(location.href); if (select.value === 'en') next.searchParams.delete('lang'); else next.searchParams.set('lang', select.value); location.href = next; });
  }
  const dict = translations[locale];
  if (!dict) return;
  document.querySelectorAll('[data-i18n]').forEach((node) => { const value = dict[node.dataset.i18n]; if (value) node.textContent = value; });
})();
