(() => {
  const supported = ["en", "es", "pt-BR", "ru", "zh-CN", "fr"];
  const params = new URLSearchParams(window.location.search);
  const requested = params.get("lang") || "en";
  const locale = supported.includes(requested) ? requested : "en";
  const products = globalThis.ROYAL_UNION_PLUMBING_PRODUCTS || [];

  const en = {
    "utility.based":"Based in Yiwu · Serving buyers worldwide","nav.home":"Home","nav.category":"Category Overview","nav.sewage":"Sewage Pipe","nav.faucet":"Faucet","nav.drain":"Drain Pipe","nav.cta":"Get a Sourcing Plan","whatsapp":"WhatsApp us","footer.copy":"China sourcing and supply-chain support for ambitious buyers worldwide.",
    "hero.kicker":"Product Categories · China Sourcing","hero.title":"Plumbing &amp;<br /><em>Bathroom Fixtures.</em>","hero.copy":"Source product ranges against clear specifications, packaging requirements and destination-market needs—then coordinate samples, orders, quality checks and consolidation through one team.","hero.primary":"Explore sewage pipe products","hero.secondary":"Send us your product brief","hero.route1":"12 products online","hero.route2":"Specification-led sourcing","hero.route3":"Project-based selection",
    "routes.eyebrow":"Three focused product routes","routes.title":"Start with the application.<br /><em>Then define the specification.</em>","routes.copy":"Plumbing products must be matched to installation, material, dimensions, connection method and local requirements. Our role is to make those details visible before an order moves forward.","routes.sewage":"Waste connectors and toilet relocation devices from the supplied catalogue.","routes.faucet":"Kitchen, basin and shower faucet sourcing based on material, finish and installation needs.","routes.drain":"Drainage components selected against the fixture, connection and project requirements.","routes.explore":"Explore products","routes.brief":"Share your brief",
    "catalog.kicker":"Subcategory 01 · Sewage Pipe","catalog.title":"Product catalogue.<br /><em>One page per item.</em>","catalog.copy":"Open a product to review the supplied specification, unit weight, packing quantity, material, packaging and carton information.","catalog.note":"Source note: values come from the uploaded product sheet. Final units, dimensions, samples and commercial terms require confirmation.","catalog.view":"View product",
    "faucet.kicker":"Faucet sourcing","faucet.title":"Define the finish.<br /><em>Control what sits underneath.</em>","faucet.copy":"For kitchen, basin and shower faucets, the visible design is only one part of the brief. Supplier comparison should also address material, cartridge, installation, finish, packaging and applicable market requirements.","faucet.item1":"Application and installation type","faucet.item2":"Body material and internal components","faucet.item3":"Surface finish and color consistency","faucet.item4":"Packaging, testing and destination requirements",
    "drain.kicker":"Drain pipe sourcing","drain.title":"Match the connection.<br /><em>Verify the whole installation.</em>","drain.copy":"Drainage products should be selected against the fixture, available space, connection dimensions, material, sealing method and maintenance expectations. Send drawings or photos whenever possible.","drain.item1":"Fixture and installation environment","drain.item2":"Dimensions and connection method","drain.item3":"Material, flexibility and sealing design","drain.item4":"Packing quantity and project schedule",
    "process.eyebrow":"How we manage the category","process.title":"A sourcing route built around<br /><em>technical confirmation.</em>","process.copy":"The objective is not to move fastest at the quotation stage. It is to make sure the supplier, sample and production order are being compared against the same brief.","process.step1":"Define the application","process.step1copy":"Share product photos, drawings, dimensions, material, quantity and destination.","process.step2":"Compare suppliers","process.step2copy":"Review product fit, specification basis, packaging and quotation conditions.","process.step3":"Approve the sample","process.step3copy":"Confirm measurements, appearance, connection and agreed reference before production.","process.step4":"Control the order","process.step4copy":"Coordinate production follow-up, checks, receiving, consolidation and delivery preparation.",
    "faq.eyebrow":"Buyer questions","faq.title":"What to confirm<br /><em>before you order.</em>","faq.copy":"These answers explain the status of the online catalogue and the information needed to start a plumbing product request.","faq.ask":"Ask about your requirement","faq.q1":"What products are included in Plumbing and Bathroom Fixtures?","faq.a1":"The category is organized into sewage pipe products, faucets and drain pipes. The current online sewage pipe catalogue includes flexible waste connectors and toilet relocation devices.","faq.q2":"Can ROYAL UNION source custom plumbing specifications?","faq.a2":"We can coordinate supplier research and quotation against required material, dimensions, connection type, finish, packaging and destination-market requirements. Feasibility must be confirmed for each request.","faq.q3":"Are the online product specifications final?","faq.a3":"No. Online values summarize the supplied product sheet. Samples, dimensions, units, packaging, applicable standards and order terms must be confirmed before purchase.","faq.q4":"Can plumbing products be consolidated with other categories?","faq.a4":"Where commercially and operationally suitable, ROYAL UNION can coordinate multi-supplier receiving and consolidation as part of an agreed sourcing plan.","faq.q5":"What should I send for a quotation?","faq.a5":"Send the product link or photo, required dimensions, material, target quantity, destination market, packaging needs and purchasing timeline.",
    "cta.kicker":"Start with a clear product brief","cta.title":"Tell us the fixture.<br /><em>We will build the sourcing route.</em>","cta.copy":"Include dimensions, material, quantity, destination market and any required packaging or testing information.",
    "product.backCategory":"Plumbing & Bathroom Fixtures","product.backSewage":"Sewage Pipe","product.catalogRef":"ROYAL UNION catalogue reference","product.leadDrain":"A plastic bathroom waste connector listed in the supplied catalogue. Review it against the required connection, dimensions, sealing design and destination-market needs.","product.leadRelocation":"A plastic toilet relocation connector listed in the supplied catalogue. Confirm installation dimensions, offset, sealing and compatibility before ordering.","product.status":"Catalogue data only: final units, dimensions, color, samples, packaging, applicable requirements and commercial terms must be confirmed before purchase.","product.imageCaption":"Product image supplied in the uploaded catalogue.","product.specTitle":"Supplied product information","spec.specification":"Specification","spec.weight":"Unit weight","spec.packing":"Packing quantity","spec.material":"Material","spec.packaging":"Factory packaging","spec.carton":"Carton information","spec.plastic":"Plastic","spec.singleBag":"Single bag packaging","spec.units":"units","product.inquire":"Request a quotation","product.back":"Back to sewage pipe catalogue","product.scopeEyebrow":"Before quotation","product.scopeTitle":"Confirm the product.<br /><em>Then compare the supplier.</em>","product.scopeCopy":"For plumbing products, photos alone are not enough. Share the intended installation and technical requirements so the sourcing route can be checked against the correct basis.","product.scope1":"Application and installation photos or drawings","product.scope2":"Required dimensions, connection and material","product.scope3":"Target quantity, packaging and destination market","product.scope4":"Testing, documents and timeline to be confirmed","product.related":"More sewage pipe products","product.disclaimer":"The product page summarizes information supplied in the uploaded workbook. It is not a final quotation, technical approval, compliance statement or warranty.",
  };

  const translations = {
    en,
    es: {
      ...en,"utility.based":"Con base en Yiwu · Atendemos a compradores de todo el mundo","nav.home":"Inicio","nav.category":"Resumen de la categoría","nav.sewage":"Tubería de evacuación","nav.faucet":"Grifería","nav.drain":"Tubería de desagüe","nav.cta":"Solicitar un plan de abastecimiento","whatsapp":"WhatsApp","footer.copy":"Abastecimiento y apoyo de cadena de suministro en China para compradores de todo el mundo.",
      "hero.kicker":"Categorías de producto · Abastecimiento en China","hero.title":"Fontanería y<br /><em>equipamiento de baño.</em>","hero.copy":"Busque gamas de productos con especificaciones, embalaje y necesidades del mercado de destino claras; después coordine muestras, pedidos, control de calidad y consolidación con un solo equipo.","hero.primary":"Ver productos de evacuación","hero.secondary":"Envíenos su ficha de producto","hero.route1":"12 productos disponibles","hero.route2":"Abastecimiento según especificaciones","hero.route3":"Selección por proyecto",
      "routes.eyebrow":"Tres rutas de producto","routes.title":"Empiece por la aplicación.<br /><em>Después defina la especificación.</em>","routes.copy":"Los productos de fontanería deben corresponder a la instalación, material, medidas, conexión y requisitos locales. Hacemos visibles estos detalles antes de avanzar.","routes.sewage":"Conectores de evacuación y desplazadores para inodoro del catálogo suministrado.","routes.faucet":"Grifería de cocina, lavabo y ducha según material, acabado e instalación.","routes.drain":"Componentes de drenaje seleccionados según el aparato, la conexión y el proyecto.","routes.explore":"Ver productos","routes.brief":"Compartir requisitos",
      "catalog.kicker":"Subcategoría 01 · Tubería de evacuación","catalog.title":"Catálogo de productos.<br /><em>Una página por artículo.</em>","catalog.copy":"Abra cada producto para revisar especificación, peso unitario, cantidad de embalaje, material, envase y caja.","catalog.note":"Nota: los valores proceden de la hoja cargada. Unidades, medidas, muestras y condiciones comerciales deben confirmarse.","catalog.view":"Ver producto",
      "faucet.kicker":"Abastecimiento de grifería","faucet.title":"Defina el acabado.<br /><em>Controle lo que hay debajo.</em>","faucet.copy":"En grifos de cocina, lavabo y ducha, el diseño visible es solo parte de la ficha. Compare también material, cartucho, instalación, acabado, embalaje y requisitos del mercado.","faucet.item1":"Aplicación y tipo de instalación","faucet.item2":"Material del cuerpo y componentes internos","faucet.item3":"Acabado superficial y consistencia del color","faucet.item4":"Embalaje, pruebas y requisitos del destino",
      "drain.kicker":"Abastecimiento de tuberías de desagüe","drain.title":"Ajuste la conexión.<br /><em>Verifique toda la instalación.</em>","drain.copy":"Seleccione el drenaje según el aparato, espacio, medidas de conexión, material, sellado y mantenimiento. Envíe planos o fotos cuando sea posible.","drain.item1":"Aparato y entorno de instalación","drain.item2":"Medidas y método de conexión","drain.item3":"Material, flexibilidad y diseño de sellado","drain.item4":"Cantidad de embalaje y calendario del proyecto",
      "process.eyebrow":"Cómo gestionamos la categoría","process.title":"Una ruta de abastecimiento basada en<br /><em>confirmación técnica.</em>","process.copy":"No se trata de cotizar lo más rápido posible, sino de comparar proveedor, muestra y producción contra la misma ficha.","process.step1":"Definir la aplicación","process.step1copy":"Comparta fotos, planos, medidas, material, cantidad y destino.","process.step2":"Comparar proveedores","process.step2copy":"Revise adecuación, base técnica, embalaje y condiciones de cotización.","process.step3":"Aprobar la muestra","process.step3copy":"Confirme medidas, aspecto, conexión y referencia antes de producir.","process.step4":"Controlar el pedido","process.step4copy":"Coordine producción, controles, recepción, consolidación y entrega.",
      "faq.eyebrow":"Preguntas del comprador","faq.title":"Qué confirmar<br /><em>antes de comprar.</em>","faq.copy":"Estas respuestas explican el estado del catálogo y la información necesaria para iniciar una solicitud.","faq.ask":"Preguntar por su requisito","faq.q1":"¿Qué incluye Fontanería y equipamiento de baño?","faq.a1":"La categoría incluye tubería de evacuación, grifería y tubería de desagüe. El catálogo actual contiene conectores flexibles y desplazadores para inodoro.","faq.q2":"¿Puede ROYAL UNION buscar especificaciones personalizadas?","faq.a2":"Podemos coordinar búsqueda y cotización según material, medidas, conexión, acabado, embalaje y mercado. La viabilidad se confirma en cada caso.","faq.q3":"¿Son definitivas las especificaciones online?","faq.a3":"No. Resumen la hoja suministrada. Muestras, medidas, unidades, embalaje, requisitos aplicables y términos deben confirmarse.","faq.q4":"¿Se pueden consolidar con otras categorías?","faq.a4":"Cuando sea comercial y operativamente adecuado, podemos coordinar recepción y consolidación de varios proveedores.","faq.q5":"¿Qué debo enviar para cotizar?","faq.a5":"Envíe enlace o foto, medidas, material, cantidad, mercado de destino, embalaje y calendario.",
      "cta.kicker":"Empiece con una ficha clara","cta.title":"Díganos el producto.<br /><em>Crearemos la ruta de abastecimiento.</em>","cta.copy":"Incluya medidas, material, cantidad, destino y requisitos de embalaje o pruebas.",
      "product.backCategory":"Fontanería y equipamiento de baño","product.backSewage":"Tubería de evacuación","product.catalogRef":"Referencia de catálogo ROYAL UNION","product.leadDrain":"Conector plástico para evacuación de baño incluido en el catálogo. Revíselo según conexión, medidas, sellado y mercado de destino.","product.leadRelocation":"Conector plástico para desplazar el inodoro incluido en el catálogo. Confirme medidas, desplazamiento, sellado y compatibilidad.","product.status":"Solo datos de catálogo: unidades, medidas, color, muestras, embalaje, requisitos aplicables y términos deben confirmarse.","product.imageCaption":"Imagen suministrada en el catálogo cargado.","product.specTitle":"Información de producto suministrada","spec.specification":"Especificación","spec.weight":"Peso unitario","spec.packing":"Cantidad de embalaje","spec.material":"Material","spec.packaging":"Embalaje de fábrica","spec.carton":"Información de caja","spec.plastic":"Plástico","spec.singleBag":"Embalaje individual en bolsa","spec.units":"unidades","product.inquire":"Solicitar cotización","product.back":"Volver al catálogo","product.scopeEyebrow":"Antes de cotizar","product.scopeTitle":"Confirme el producto.<br /><em>Después compare el proveedor.</em>","product.scopeCopy":"Las fotos no bastan. Comparta instalación y requisitos técnicos para comparar sobre la base correcta.","product.scope1":"Aplicación y fotos o planos de instalación","product.scope2":"Medidas, conexión y material requeridos","product.scope3":"Cantidad, embalaje y mercado de destino","product.scope4":"Pruebas, documentos y calendario por confirmar","product.related":"Más productos de evacuación","product.disclaimer":"Esta página resume la hoja cargada. No constituye cotización final, aprobación técnica, declaración de cumplimiento ni garantía."
    },
    "pt-BR": {
      ...en,"utility.based":"Baseados em Yiwu · Atendendo compradores no mundo todo","nav.home":"Início","nav.category":"Visão da categoria","nav.sewage":"Tubos de esgoto","nav.faucet":"Torneiras","nav.drain":"Tubos de drenagem","nav.cta":"Solicitar plano de sourcing","whatsapp":"WhatsApp","footer.copy":"Sourcing e suporte de cadeia de suprimentos na China para compradores globais.",
      "hero.kicker":"Categorias de produtos · Sourcing na China","hero.title":"Hidráulica e<br /><em>acessórios para banheiro.</em>","hero.copy":"Busque linhas com especificações, embalagem e mercado de destino definidos e coordene amostras, pedidos, qualidade e consolidação com uma só equipe.","hero.primary":"Ver produtos de esgoto","hero.secondary":"Enviar briefing do produto","hero.route1":"12 produtos online","hero.route2":"Sourcing por especificação","hero.route3":"Seleção por projeto",
      "routes.eyebrow":"Três rotas de produto","routes.title":"Comece pela aplicação.<br /><em>Depois defina a especificação.</em>","routes.copy":"Produtos hidráulicos devem corresponder à instalação, material, medidas, conexão e requisitos locais. Tornamos esses detalhes visíveis antes do pedido.","routes.sewage":"Conectores de esgoto e deslocadores para vaso sanitário do catálogo fornecido.","routes.faucet":"Torneiras de cozinha, lavatório e chuveiro conforme material, acabamento e instalação.","routes.drain":"Componentes de drenagem escolhidos conforme louça, conexão e projeto.","routes.explore":"Ver produtos","routes.brief":"Enviar briefing",
      "catalog.kicker":"Subcategoria 01 · Tubos de esgoto","catalog.title":"Catálogo de produtos.<br /><em>Uma página para cada item.</em>","catalog.copy":"Abra o produto para ver especificação, peso, quantidade, material, embalagem e caixa fornecidos.","catalog.note":"Nota: os valores vêm da planilha enviada. Unidades, medidas, amostras e termos comerciais precisam ser confirmados.","catalog.view":"Ver produto",
      "faucet.kicker":"Sourcing de torneiras","faucet.title":"Defina o acabamento.<br /><em>Controle o que está por dentro.</em>","faucet.copy":"Em torneiras de cozinha, lavatório e chuveiro, o design é apenas parte do briefing. Compare material, cartucho, instalação, acabamento, embalagem e requisitos do mercado.","faucet.item1":"Aplicação e tipo de instalação","faucet.item2":"Material do corpo e componentes internos","faucet.item3":"Acabamento e consistência de cor","faucet.item4":"Embalagem, testes e requisitos do destino",
      "drain.kicker":"Sourcing de tubos de drenagem","drain.title":"Combine a conexão.<br /><em>Verifique toda a instalação.</em>","drain.copy":"Selecione a drenagem conforme louça, espaço, medidas, material, vedação e manutenção. Envie desenhos ou fotos sempre que possível.","drain.item1":"Louça e ambiente de instalação","drain.item2":"Medidas e método de conexão","drain.item3":"Material, flexibilidade e vedação","drain.item4":"Quantidade por embalagem e cronograma",
      "process.eyebrow":"Como gerenciamos a categoria","process.title":"Uma rota de sourcing baseada em<br /><em>confirmação técnica.</em>","process.copy":"O objetivo não é apenas cotar rápido, mas comparar fornecedor, amostra e produção com o mesmo briefing.","process.step1":"Definir a aplicação","process.step1copy":"Envie fotos, desenhos, medidas, material, quantidade e destino.","process.step2":"Comparar fornecedores","process.step2copy":"Revise adequação, base técnica, embalagem e condições da cotação.","process.step3":"Aprovar a amostra","process.step3copy":"Confirme medidas, aparência, conexão e referência antes da produção.","process.step4":"Controlar o pedido","process.step4copy":"Coordene produção, inspeções, recebimento, consolidação e entrega.",
      "faq.eyebrow":"Perguntas do comprador","faq.title":"O que confirmar<br /><em>antes de comprar.</em>","faq.copy":"Estas respostas explicam o catálogo e os dados necessários para iniciar uma solicitação.","faq.ask":"Perguntar sobre seu requisito","faq.q1":"O que está incluído em Hidráulica e acessórios para banheiro?","faq.a1":"A categoria inclui tubos de esgoto, torneiras e tubos de drenagem. O catálogo atual contém conectores flexíveis e deslocadores para vaso sanitário.","faq.q2":"A ROYAL UNION busca especificações personalizadas?","faq.a2":"Podemos coordenar pesquisa e cotação por material, medidas, conexão, acabamento, embalagem e mercado. A viabilidade é confirmada em cada projeto.","faq.q3":"As especificações online são finais?","faq.a3":"Não. Elas resumem a planilha. Amostras, medidas, unidades, embalagem, requisitos aplicáveis e termos devem ser confirmados.","faq.q4":"É possível consolidar com outras categorias?","faq.a4":"Quando comercial e operacionalmente adequado, podemos coordenar recebimento e consolidação de vários fornecedores.","faq.q5":"O que enviar para cotação?","faq.a5":"Envie link ou foto, medidas, material, quantidade, destino, embalagem e prazo.",
      "cta.kicker":"Comece com um briefing claro","cta.title":"Diga qual é o produto.<br /><em>Nós montamos a rota de sourcing.</em>","cta.copy":"Inclua medidas, material, quantidade, destino e requisitos de embalagem ou teste.",
      "product.backCategory":"Hidráulica e acessórios para banheiro","product.backSewage":"Tubos de esgoto","product.catalogRef":"Referência de catálogo ROYAL UNION","product.leadDrain":"Conector plástico para esgoto de banheiro listado no catálogo. Compare conexão, medidas, vedação e mercado de destino.","product.leadRelocation":"Conector plástico para deslocamento de vaso sanitário. Confirme medidas, deslocamento, vedação e compatibilidade.","product.status":"Dados de catálogo: unidades, medidas, cor, amostras, embalagem, requisitos aplicáveis e termos precisam ser confirmados.","product.imageCaption":"Imagem fornecida no catálogo enviado.","product.specTitle":"Informações fornecidas do produto","spec.specification":"Especificação","spec.weight":"Peso unitário","spec.packing":"Quantidade por embalagem","spec.material":"Material","spec.packaging":"Embalagem de fábrica","spec.carton":"Informação da caixa","spec.plastic":"Plástico","spec.singleBag":"Embalagem individual em saco","spec.units":"unidades","product.inquire":"Solicitar cotação","product.back":"Voltar ao catálogo","product.scopeEyebrow":"Antes da cotação","product.scopeTitle":"Confirme o produto.<br /><em>Depois compare o fornecedor.</em>","product.scopeCopy":"Fotos não bastam. Envie instalação e requisitos técnicos para comparar na base correta.","product.scope1":"Aplicação e fotos ou desenhos da instalação","product.scope2":"Medidas, conexão e material necessários","product.scope3":"Quantidade, embalagem e mercado de destino","product.scope4":"Testes, documentos e prazo a confirmar","product.related":"Mais produtos de esgoto","product.disclaimer":"A página resume a planilha enviada. Não é cotação final, aprovação técnica, declaração de conformidade ou garantia."
    },
    ru: {
      ...en,"utility.based":"Иу, Китай · Работаем с покупателями по всему миру","nav.home":"Главная","nav.category":"Обзор категории","nav.sewage":"Канализационные трубы","nav.faucet":"Смесители","nav.drain":"Сливные трубы","nav.cta":"Получить план закупки","whatsapp":"WhatsApp","footer.copy":"Закупки и поддержка цепочки поставок в Китае для международных покупателей.",
      "hero.kicker":"Категории товаров · Закупки в Китае","hero.title":"Сантехника и<br /><em>оборудование для ванной.</em>","hero.copy":"Подбирайте товары по чётким спецификациям, упаковке и требованиям рынка, а затем координируйте образцы, заказы, качество и консолидацию через одну команду.","hero.primary":"Смотреть канализационные товары","hero.secondary":"Отправить техническое задание","hero.route1":"12 товаров онлайн","hero.route2":"Закупка по спецификации","hero.route3":"Подбор под проект",
      "routes.eyebrow":"Три товарных направления","routes.title":"Начните с применения.<br /><em>Затем задайте спецификацию.</em>","routes.copy":"Сантехнические товары должны соответствовать монтажу, материалу, размерам, соединению и местным требованиям. Мы фиксируем эти детали до заказа.","routes.sewage":"Сливные соединители и переходники для унитаза из предоставленного каталога.","routes.faucet":"Смесители для кухни, раковины и душа по материалу, покрытию и монтажу.","routes.drain":"Дренажные компоненты по сантехнике, соединению и проекту.","routes.explore":"Смотреть товары","routes.brief":"Отправить задание",
      "catalog.kicker":"Подкатегория 01 · Канализационные трубы","catalog.title":"Каталог товаров.<br /><em>Отдельная страница для каждого.</em>","catalog.copy":"Откройте товар, чтобы увидеть спецификацию, вес, количество, материал, упаковку и данные коробки.","catalog.note":"Примечание: данные взяты из загруженной таблицы. Единицы, размеры, образцы и коммерческие условия нужно подтвердить.","catalog.view":"Открыть товар",
      "faucet.kicker":"Закупка смесителей","faucet.title":"Задайте покрытие.<br /><em>Проверьте внутренние детали.</em>","faucet.copy":"Для кухонных, умывальных и душевых смесителей важен не только дизайн. Сравнивайте материал, картридж, монтаж, покрытие, упаковку и требования рынка.","faucet.item1":"Назначение и тип монтажа","faucet.item2":"Материал корпуса и внутренние детали","faucet.item3":"Покрытие и стабильность цвета","faucet.item4":"Упаковка, испытания и требования рынка",
      "drain.kicker":"Закупка сливных труб","drain.title":"Согласуйте соединение.<br /><em>Проверьте весь монтаж.</em>","drain.copy":"Дренаж выбирают по сантехнике, пространству, размерам, материалу, уплотнению и обслуживанию. По возможности отправьте чертежи или фото.","drain.item1":"Сантехника и условия монтажа","drain.item2":"Размеры и способ соединения","drain.item3":"Материал, гибкость и уплотнение","drain.item4":"Количество в упаковке и график проекта",
      "process.eyebrow":"Как мы управляем категорией","process.title":"Маршрут закупки с опорой на<br /><em>техническое подтверждение.</em>","process.copy":"Цель — не только быстро получить цену, а сравнить поставщика, образец и производство по одному заданию.","process.step1":"Определить применение","process.step1copy":"Отправьте фото, чертежи, размеры, материал, количество и страну.","process.step2":"Сравнить поставщиков","process.step2copy":"Проверьте соответствие, спецификацию, упаковку и условия цены.","process.step3":"Утвердить образец","process.step3copy":"Подтвердите размеры, вид, соединение и эталон до производства.","process.step4":"Контролировать заказ","process.step4copy":"Координируйте производство, проверки, приёмку, консолидацию и доставку.",
      "faq.eyebrow":"Вопросы покупателя","faq.title":"Что подтвердить<br /><em>до заказа.</em>","faq.copy":"Ответы объясняют статус каталога и данные для начала запроса.","faq.ask":"Задать вопрос","faq.q1":"Что входит в категорию сантехники и ванной?","faq.a1":"Категория включает канализационные трубы, смесители и сливные трубы. В текущем каталоге есть гибкие соединители и переходники для унитаза.","faq.q2":"Может ли ROYAL UNION искать нестандартные спецификации?","faq.a2":"Мы можем координировать поиск и расчёт по материалу, размерам, соединению, покрытию, упаковке и рынку. Возможность подтверждается отдельно.","faq.q3":"Онлайн-спецификации окончательные?","faq.a3":"Нет. Это сводка таблицы. Образцы, размеры, единицы, упаковка, требования и условия нужно подтвердить.","faq.q4":"Можно ли консолидировать с другими категориями?","faq.a4":"Когда это коммерчески и операционно целесообразно, мы координируем приёмку и консолидацию нескольких поставщиков.","faq.q5":"Что отправить для расчёта?","faq.a5":"Ссылку или фото, размеры, материал, количество, рынок, упаковку и срок.",
      "cta.kicker":"Начните с ясного задания","cta.title":"Опишите товар.<br /><em>Мы построим маршрут закупки.</em>","cta.copy":"Укажите размеры, материал, количество, рынок и требования к упаковке или испытаниям.",
      "product.backCategory":"Сантехника и оборудование для ванной","product.backSewage":"Канализационные трубы","product.catalogRef":"Каталожный номер ROYAL UNION","product.leadDrain":"Пластиковый соединитель для слива из каталога. Сверьте соединение, размеры, уплотнение и требования рынка.","product.leadRelocation":"Пластиковый переходник для смещения унитаза. Подтвердите размеры, смещение, уплотнение и совместимость.","product.status":"Только каталожные данные: единицы, размеры, цвет, образцы, упаковку, требования и условия нужно подтвердить.","product.imageCaption":"Изображение из загруженного каталога.","product.specTitle":"Предоставленная информация о товаре","spec.specification":"Спецификация","spec.weight":"Вес единицы","spec.packing":"Количество в упаковке","spec.material":"Материал","spec.packaging":"Заводская упаковка","spec.carton":"Данные коробки","spec.plastic":"Пластик","spec.singleBag":"Индивидуальная упаковка в пакет","spec.units":"шт.","product.inquire":"Запросить цену","product.back":"Назад к каталогу","product.scopeEyebrow":"До расчёта","product.scopeTitle":"Подтвердите товар.<br /><em>Затем сравните поставщика.</em>","product.scopeCopy":"Одних фото недостаточно. Отправьте данные монтажа и технические требования.","product.scope1":"Назначение и фото или чертежи монтажа","product.scope2":"Размеры, соединение и материал","product.scope3":"Количество, упаковка и рынок","product.scope4":"Испытания, документы и срок для подтверждения","product.related":"Другие канализационные товары","product.disclaimer":"Страница суммирует загруженную таблицу и не является окончательной ценой, техническим одобрением, декларацией соответствия или гарантией."
    },
    "zh-CN": {
      ...en,"utility.based":"扎根义乌 · 服务全球采购商","nav.home":"首页","nav.category":"类目概览","nav.sewage":"排污管","nav.faucet":"水龙头","nav.drain":"下水管","nav.cta":"获取采购方案","whatsapp":"WhatsApp 联系我们","footer.copy":"为全球采购商提供中国采购与供应链支持。",
      "hero.kicker":"产品类目 · 中国采购","hero.title":"管道与<br /><em>卫浴五金。</em>","hero.copy":"围绕明确的规格、包装和目的地市场要求开展产品采购，并由同一团队协调样品、订单、质量检查与集货整合。","hero.primary":"查看排污管产品","hero.secondary":"提交产品需求","hero.route1":"12款产品已上线","hero.route2":"按规格开展采购","hero.route3":"按项目匹配产品",
      "routes.eyebrow":"三个重点产品方向","routes.title":"先确认使用场景，<br /><em>再明确产品规格。</em>","routes.copy":"管道卫浴产品必须与安装环境、材质、尺寸、连接方式及当地要求相匹配。我们的工作是在下单前把这些细节确认清楚。","routes.sewage":"已上传目录中的排污连接管与马桶移位器。","routes.faucet":"根据材质、表面处理和安装方式采购厨房、面盆及淋浴水龙头。","routes.drain":"根据卫浴产品、连接方式及项目要求匹配下水部件。","routes.explore":"查看产品","routes.brief":"提交需求",
      "catalog.kicker":"子类目 01 · 排污管","catalog.title":"产品目录。<br /><em>每款产品独立页面。</em>","catalog.copy":"点击产品可查看资料表中提供的规格、单重、装箱数量、材质、工厂包装和外箱信息。","catalog.note":"资料说明：页面数据来自您上传的产品表。最终单位、尺寸、样品和商务条款需在下单前确认。","catalog.view":"查看产品",
      "faucet.kicker":"水龙头采购","faucet.title":"确认外观处理，<br /><em>也要核对内部结构。</em>","faucet.copy":"厨房、面盆和淋浴水龙头不能只看外观。供应商对比还需涵盖材质、阀芯、安装方式、表面处理、包装及市场要求。","faucet.item1":"使用场景与安装方式","faucet.item2":"主体材质与内部配件","faucet.item3":"表面处理与颜色一致性","faucet.item4":"包装、测试与目的地要求",
      "drain.kicker":"下水管采购","drain.title":"匹配连接方式，<br /><em>核对整体安装条件。</em>","drain.copy":"下水产品需根据卫浴产品、安装空间、连接尺寸、材质、密封方式及维护需求进行选择。建议尽量提供图纸或现场照片。","drain.item1":"适配产品与安装环境","drain.item2":"尺寸与连接方式","drain.item3":"材质、柔韧性与密封结构","drain.item4":"装箱数量与项目进度",
      "process.eyebrow":"我们的类目管理方式","process.title":"以技术确认为核心的<br /><em>采购执行路径。</em>","process.copy":"重点不是报价阶段追求最快，而是确保供应商、样品和大货订单都基于同一份需求进行比较。","process.step1":"明确使用场景","process.step1copy":"提供产品照片、图纸、尺寸、材质、数量和目的地。","process.step2":"对比供应商","process.step2copy":"核对产品适配性、规格基础、包装和报价条件。","process.step3":"确认样品","process.step3copy":"生产前确认尺寸、外观、连接方式和批准样。","process.step4":"管控订单","process.step4copy":"协调生产跟进、检查、收货、集货和出运准备。",
      "faq.eyebrow":"采购商常见问题","faq.title":"下单前<br /><em>需要确认什么。</em>","faq.copy":"以下内容说明线上目录的数据状态，以及开始管道卫浴产品询价所需的信息。","faq.ask":"咨询您的产品需求","faq.q1":"Plumbing and Bathroom Fixtures 包含哪些产品？","faq.a1":"该类目分为排污管、水龙头和下水管。目前上线的排污管目录包含柔性排污连接管与马桶移位器。","faq.q2":"ROYAL UNION 可以按定制规格采购吗？","faq.a2":"我们可以围绕材质、尺寸、连接方式、表面处理、包装和目的地市场要求协调供应商搜索与报价，具体可行性需逐项确认。","faq.q3":"线上规格是最终规格吗？","faq.a3":"不是。线上数据是对上传资料表的整理。样品、尺寸、单位、包装、适用要求和订单条款必须在采购前确认。","faq.q4":"可以和其他类目一起集货吗？","faq.a4":"在商业和操作条件适合的情况下，ROYAL UNION 可以在采购方案中协调多供应商收货与集货。","faq.q5":"询价需要提供什么？","faq.a5":"请提供产品链接或照片、所需尺寸、材质、目标数量、目的地市场、包装要求和采购时间。",
      "cta.kicker":"从清晰的产品需求开始","cta.title":"告诉我们产品要求，<br /><em>我们来规划采购路径。</em>","cta.copy":"请提供尺寸、材质、数量、目的地市场以及包装或测试要求。",
      "product.backCategory":"管道与卫浴五金","product.backSewage":"排污管","product.catalogRef":"ROYAL UNION 产品目录编号","product.leadDrain":"资料表中列出的塑料卫浴排污连接管。询价前需根据连接方式、尺寸、密封结构和目的地市场要求进行核对。","product.leadRelocation":"资料表中列出的塑料马桶移位连接件。下单前需确认安装尺寸、移位距离、密封方式和适配性。","product.status":"当前仅为目录数据：最终单位、尺寸、颜色、样品、包装、适用要求和商务条款需在采购前确认。","product.imageCaption":"图片来自您上传的产品目录。","product.specTitle":"资料表提供的产品信息","spec.specification":"规格","spec.weight":"单重","spec.packing":"装箱数量","spec.material":"材质","spec.packaging":"工厂包装","spec.carton":"外箱信息","spec.plastic":"塑料","spec.singleBag":"单个袋装","spec.units":"个","product.inquire":"询价此产品","product.back":"返回排污管目录","product.scopeEyebrow":"询价前","product.scopeTitle":"先确认产品，<br /><em>再对比供应商。</em>","product.scopeCopy":"管道卫浴产品不能只看图片。请提供安装场景与技术要求，以便按正确标准开展供应商对比。","product.scope1":"使用场景及安装照片或图纸","product.scope2":"所需尺寸、连接方式和材质","product.scope3":"目标数量、包装和目的地市场","product.scope4":"需确认的测试、文件与时间要求","product.related":"更多排污管产品","product.disclaimer":"本产品页仅整理上传表格中的信息，不构成最终报价、技术批准、合规声明或质量保证。"
    },
    fr: {
      ...en,"utility.based":"Basés à Yiwu · Au service des acheteurs du monde entier","nav.home":"Accueil","nav.category":"Vue de la catégorie","nav.sewage":"Évacuation sanitaire","nav.faucet":"Robinetterie","nav.drain":"Tuyaux d’évacuation","nav.cta":"Obtenir un plan de sourcing","whatsapp":"WhatsApp","footer.copy":"Sourcing en Chine et soutien de chaîne d’approvisionnement pour les acheteurs internationaux.",
      "hero.kicker":"Catégories de produits · Sourcing en Chine","hero.title":"Plomberie et<br /><em>équipements de salle de bains.</em>","hero.copy":"Sourcez des gammes selon des spécifications, emballages et marchés clairement définis, puis coordonnez échantillons, commandes, qualité et consolidation avec une seule équipe.","hero.primary":"Voir les produits d’évacuation","hero.secondary":"Envoyer votre cahier des charges","hero.route1":"12 produits en ligne","hero.route2":"Sourcing selon spécification","hero.route3":"Sélection par projet",
      "routes.eyebrow":"Trois axes produits","routes.title":"Commencez par l’usage.<br /><em>Définissez ensuite la spécification.</em>","routes.copy":"Les produits de plomberie doivent correspondre à l’installation, au matériau, aux dimensions, au raccordement et aux exigences locales. Nous rendons ces détails visibles avant la commande.","routes.sewage":"Raccords d’évacuation et raccords excentrés pour WC du catalogue fourni.","routes.faucet":"Robinets de cuisine, lavabo et douche selon matériau, finition et installation.","routes.drain":"Composants de drainage choisis selon l’équipement, le raccord et le projet.","routes.explore":"Voir les produits","routes.brief":"Partager le besoin",
      "catalog.kicker":"Sous-catégorie 01 · Évacuation sanitaire","catalog.title":"Catalogue produits.<br /><em>Une page par référence.</em>","catalog.copy":"Ouvrez un produit pour voir spécification, poids, quantité, matériau, emballage et carton fournis.","catalog.note":"Note : les valeurs viennent du fichier chargé. Unités, dimensions, échantillons et conditions commerciales doivent être confirmés.","catalog.view":"Voir le produit",
      "faucet.kicker":"Sourcing de robinetterie","faucet.title":"Définissez la finition.<br /><em>Contrôlez aussi l’intérieur.</em>","faucet.copy":"Pour les robinets de cuisine, lavabo et douche, le design n’est qu’une partie du besoin. Comparez aussi matériau, cartouche, pose, finition, emballage et exigences du marché.","faucet.item1":"Usage et type d’installation","faucet.item2":"Matériau du corps et composants internes","faucet.item3":"Finition et régularité de couleur","faucet.item4":"Emballage, essais et exigences du marché",
      "drain.kicker":"Sourcing de tuyaux d’évacuation","drain.title":"Adaptez le raccord.<br /><em>Vérifiez toute l’installation.</em>","drain.copy":"Choisissez le drainage selon l’équipement, l’espace, les dimensions, le matériau, l’étanchéité et l’entretien. Envoyez des plans ou photos si possible.","drain.item1":"Équipement et environnement de pose","drain.item2":"Dimensions et méthode de raccordement","drain.item3":"Matériau, flexibilité et étanchéité","drain.item4":"Quantité d’emballage et calendrier",
      "process.eyebrow":"Notre gestion de la catégorie","process.title":"Un parcours de sourcing fondé sur<br /><em>la confirmation technique.</em>","process.copy":"L’objectif n’est pas seulement de chiffrer vite, mais de comparer fournisseur, échantillon et production sur le même cahier des charges.","process.step1":"Définir l’usage","process.step1copy":"Envoyez photos, plans, dimensions, matériau, quantité et destination.","process.step2":"Comparer les fournisseurs","process.step2copy":"Vérifiez adaptation, base technique, emballage et conditions du devis.","process.step3":"Approuver l’échantillon","process.step3copy":"Confirmez dimensions, aspect, raccord et référence avant production.","process.step4":"Contrôler la commande","process.step4copy":"Coordonnez production, contrôles, réception, consolidation et livraison.",
      "faq.eyebrow":"Questions acheteurs","faq.title":"Que confirmer<br /><em>avant la commande.</em>","faq.copy":"Ces réponses expliquent le statut du catalogue et les informations nécessaires pour démarrer.","faq.ask":"Poser une question","faq.q1":"Que comprend la catégorie Plomberie et salle de bains ?","faq.a1":"Elle comprend évacuation sanitaire, robinetterie et tuyaux d’évacuation. Le catalogue actuel contient des raccords flexibles et des raccords excentrés pour WC.","faq.q2":"ROYAL UNION peut-elle sourcer des spécifications personnalisées ?","faq.a2":"Nous pouvons coordonner recherche et devis selon matériau, dimensions, raccord, finition, emballage et marché. La faisabilité est confirmée par projet.","faq.q3":"Les spécifications en ligne sont-elles définitives ?","faq.a3":"Non. Elles résument le fichier fourni. Échantillons, dimensions, unités, emballage, exigences applicables et conditions doivent être confirmés.","faq.q4":"Peut-on consolider avec d’autres catégories ?","faq.a4":"Lorsque cela est adapté commercialement et opérationnellement, nous pouvons coordonner réception et consolidation multi-fournisseurs.","faq.q5":"Que fournir pour un devis ?","faq.a5":"Lien ou photo, dimensions, matériau, quantité, marché, emballage et calendrier.",
      "cta.kicker":"Commencez par un besoin clair","cta.title":"Décrivez le produit.<br /><em>Nous construirons le parcours de sourcing.</em>","cta.copy":"Précisez dimensions, matériau, quantité, destination et exigences d’emballage ou d’essai.",
      "product.backCategory":"Plomberie et équipements de salle de bains","product.backSewage":"Évacuation sanitaire","product.catalogRef":"Référence catalogue ROYAL UNION","product.leadDrain":"Raccord plastique d’évacuation de salle de bains listé dans le catalogue. Vérifiez raccord, dimensions, étanchéité et marché de destination.","product.leadRelocation":"Raccord plastique excentré pour WC listé dans le catalogue. Confirmez dimensions, décalage, étanchéité et compatibilité.","product.status":"Données de catalogue uniquement : unités, dimensions, couleur, échantillons, emballage, exigences et conditions doivent être confirmés.","product.imageCaption":"Image fournie dans le catalogue chargé.","product.specTitle":"Informations produit fournies","spec.specification":"Spécification","spec.weight":"Poids unitaire","spec.packing":"Quantité d’emballage","spec.material":"Matériau","spec.packaging":"Emballage usine","spec.carton":"Informations carton","spec.plastic":"Plastique","spec.singleBag":"Emballage individuel en sachet","spec.units":"unités","product.inquire":"Demander un devis","product.back":"Retour au catalogue","product.scopeEyebrow":"Avant le devis","product.scopeTitle":"Confirmez le produit.<br /><em>Puis comparez le fournisseur.</em>","product.scopeCopy":"Les photos seules ne suffisent pas. Envoyez l’installation et les exigences techniques pour comparer sur la bonne base.","product.scope1":"Usage et photos ou plans d’installation","product.scope2":"Dimensions, raccord et matériau requis","product.scope3":"Quantité, emballage et marché","product.scope4":"Essais, documents et délai à confirmer","product.related":"Autres produits d’évacuation","product.disclaimer":"Cette page résume le fichier chargé. Elle ne constitue ni devis final, ni approbation technique, ni déclaration de conformité, ni garantie."
    }
  };

  const strings = translations[locale] || en;
  document.documentElement.lang = locale;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = strings[element.dataset.i18n];
    if (value) element.textContent = value;
  });
  document.querySelectorAll("[data-i18n-html]").forEach((element) => {
    const value = strings[element.dataset.i18nHtml];
    if (value) element.innerHTML = value;
  });
  document.querySelectorAll("[data-product-name]").forEach((element) => {
    const product = products.find((item) => item.id === element.dataset.productName);
    if (product) element.textContent = product.names[locale] || product.names.en;
  });

  const productId = document.body.dataset.productId;
  const product = products.find((item) => item.id === productId);
  if (product) {
    const name = product.names[locale] || product.names.en;
    document.querySelectorAll("[data-current-product-name]").forEach((element) => { element.textContent = name; });
    document.querySelectorAll("[data-current-product-code]").forEach((element) => { element.textContent = product.code; });
    const lead = product.kind === "relocationDevice" ? strings["product.leadRelocation"] : strings["product.leadDrain"];
    document.querySelectorAll("[data-product-lead]").forEach((element) => { element.textContent = lead; });
    const title = `${name} | ROYAL UNION`;
    const description = `${name}: supplied specifications, packing information and China sourcing enquiry with ROYAL UNION.`;
    document.title = title;
    document.querySelector('meta[name="description"]')?.setAttribute("content", description);
    document.querySelector('meta[property="og:title"]')?.setAttribute("content", title);
    document.querySelector('meta[property="og:description"]')?.setAttribute("content", description);
    document.querySelector('meta[name="twitter:title"]')?.setAttribute("content", title);
    document.querySelector('meta[name="twitter:description"]')?.setAttribute("content", description);
  } else if (document.body.classList.contains("plumbing-page")) {
    const localizedTitles = { en:"Plumbing & Bathroom Fixtures Sourcing | ROYAL UNION", es:"Fontanería y equipamiento de baño | ROYAL UNION", "pt-BR":"Hidráulica e acessórios para banheiro | ROYAL UNION", ru:"Сантехника и оборудование для ванной | ROYAL UNION", "zh-CN":"管道与卫浴五金采购 | ROYAL UNION", fr:"Plomberie et équipements de salle de bains | ROYAL UNION" };
    document.title = localizedTitles[locale];
    document.querySelector('meta[property="og:title"]')?.setAttribute("content", localizedTitles[locale]);
    document.querySelector('meta[name="twitter:title"]')?.setAttribute("content", localizedTitles[locale]);
  }

  const select = document.querySelector("#language-select");
  if (select) {
    select.value = locale;
    select.addEventListener("change", () => {
      const next = new URL(window.location.href);
      if (select.value === "en") next.searchParams.delete("lang");
      else next.searchParams.set("lang", select.value);
      window.location.assign(next.href);
    });
  }

  if (locale !== "en") {
    document.querySelectorAll("a[href]").forEach((link) => {
      const href = link.getAttribute("href");
      if (!href || href.startsWith("#") || href.startsWith("mailto:") || href.startsWith("tel:") || href.startsWith("https://wa.me/")) return;
      const url = new URL(href, window.location.href);
      if (url.protocol !== "http:" && url.protocol !== "https:" && url.protocol !== "file:") return;
      if (url.protocol !== "file:" && url.origin !== window.location.origin) return;
      url.searchParams.set("lang", locale);
      link.href = url.href;
    });
  }
})();
